# Generated by Django 6.0.2 on 2026-02-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Passenger",
            fields=[
                ("passage_id", models.AutoField(primary_key=True, serialize=False)),
                ("survived", models.BooleanField()),
                ("pclass", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("sex", models.CharField(max_length=10)),
                ("age", models.FloatField(blank=True, null=True)),
                ("sibsp", models.IntegerField(default=0)),
                ("parch", models.IntegerField(default=0)),
                ("fare", models.FloatField(blank=True, null=True)),
                ("embarked", models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                "db_table": "passengers",
            },
        ),
    ]
